include: "rule/00_common.smk"

rule all:
	input:
		###################  hifiasm  ##################
		#expand("results/02_assembly/02_hifi_asm/{sample}_hifiasm.hic.p_ctg.fa",sample = Psample),
		#expand("results/02_assembly/03_hic/02_ref/{sample}_hifiasm.hic.p_ctg.fa",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.p_ctg",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.hap1.p_ctg",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.hap2.p_ctg",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.p_ctg_n10_n90",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.hap1.p_ctg_n10_n90",sample = Psample),
		#expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.hap2.p_ctg_n10_n90",sample = Psample),
		#expand("results/03_assembly_assement/02_busco/{sample}_hifiasm.hic.p_ctg/short_summary.specific.solanales_odb10.{sample}_hifiasm.hic.p_ctg.txt",sample = Psample),
		expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.p_ctg_clean", sample = Psample),
		expand("results/03_assembly_assement/01_seqkit_stats/{sample}_hifiasm.hic.p_ctg_clean_n10_n90", sample = Psample),
		expand("results/03_assembly_assement/02_busco/{sample}_hifiasm.hic.p_ctg_clean/short_summary.specific.solanales_odb10.{sample}_hifiasm.hic.p_ctg_clean.txt", sample = Psample),
		###################  HiC  ##################
		expand("cleandata/03_hic/{sample}_clean_{n}.fq.gz", sample = Hsample, n = HAP),
		expand("results/02_assembly/03_hic/01_qc/02_fastqc/{sample}_clean_{n}_fastqc.html", sample = Hsample, n = HAP),
		expand("results/02_assembly/03_hic/01_qc/02_fastqc/{sample}_clean_{n}_fastqc.zip", sample = Hsample, n = HAP),
		expand("results/02_assembly/03_hic/02_ref/{sample}_{enzyme}.txt", sample=Psample,enzyme=enzyme),
		expand("results/02_assembly/03_hic/04_merge/{sample}.merged_nodups.txt",sample=Psample),
		expand("results/02_assembly/03_hic/05_3d-dna/{sample}_hifiasm.hic.p_ctg_clean.0.hic", sample=Psample),
		expand("results/02_assembly/03_hic/06_End_hic/{sample}_hicPro/hic_results/matrix/{sample}/iced/1000000/{sample}_1000000_iced.matrix", sample = Psample)


#include: "rule/02_hifi_asm.smk"
include: "rule/03_clean.smk"
include: "rule/04_hic.smk"
include: "rule/05_End_hic.smk"
