######################################
#
# BUSCO summary figure
# @version 4.0.0
# @since BUSCO 2.0.0
# 
# Copyright (c) 2016-2021, Evgeny Zdobnov (ez@ezlab.org)
# Licensed under the MIT license. See LICENSE.md file.
#
######################################

# Load the required libraries
library(ggplot2)
library("grid")

# !!! CONFIGURE YOUR PLOT HERE !!! 
# Output
my_output <- paste("/vol3/agis/huangsanwen_group/wuyaoyao/03-Solanaceae/03-Assembly/Busco_summary/","busco_figure.png",sep="/") 
my_width <- 20
my_height <- 15
my_unit <- "cm"

# Colors
my_colors <- c("#56B4E9", "#3492C7", "#F0E442", "#F04442")
# Bar height ratio
my_bar_height <- 0.75

# Legend
my_title <- "BUSCO Assessment Results"

# Font
my_family <- "sans"
my_size_ratio <- 1

# !!! SEE YOUR DATA HERE !!! 
# Your data as generated by python, remove or add more
my_species <- c('Solanum_japonense_final_busco', 'Solanum_japonense_final_busco', 'Solanum_japonense_final_busco', 'Solanum_japonense_final_busco', 'Datura_metel_final_busco', 'Datura_metel_final_busco', 'Datura_metel_final_busco', 'Datura_metel_final_busco', 'Solanum_aculeatissimum_final_busco', 'Solanum_aculeatissimum_final_busco', 'Solanum_aculeatissimum_final_busco', 'Solanum_aculeatissimum_final_busco', 'Solanum_retroflexum_final_busco', 'Solanum_retroflexum_final_busco', 'Solanum_retroflexum_final_busco', 'Solanum_retroflexum_final_busco', 'Us6_final_busco', 'Us6_final_busco', 'Us6_final_busco', 'Us6_final_busco', 'Yn15_final_busco', 'Yn15_final_busco', 'Yn15_final_busco', 'Yn15_final_busco', 'Yn1_final_busco', 'Yn1_final_busco', 'Yn1_final_busco', 'Yn1_final_busco', 'Yn30_final_busco', 'Yn30_final_busco', 'Yn30_final_busco', 'Yn30_final_busco', 'Datura_inoxia_final_busco', 'Datura_inoxia_final_busco', 'Datura_inoxia_final_busco', 'Datura_inoxia_final_busco', 'Solanum_anguivi_final_busco', 'Solanum_anguivi_final_busco', 'Solanum_anguivi_final_busco', 'Solanum_anguivi_final_busco', 'Solanum_dulcamara_final_busco', 'Solanum_dulcamara_final_busco', 'Solanum_dulcamara_final_busco', 'Solanum_dulcamara_final_busco', 'Solanum_merrillianum_final_busco', 'Solanum_merrillianum_final_busco', 'Solanum_merrillianum_final_busco', 'Solanum_merrillianum_final_busco', 'Physalis_angulata_final_busco', 'Physalis_angulata_final_busco', 'Physalis_angulata_final_busco', 'Physalis_angulata_final_busco', 'solanum_aviculare_final_busco', 'solanum_aviculare_final_busco', 'solanum_aviculare_final_busco', 'solanum_aviculare_final_busco', 'Datura_stramonium_final_busco', 'Datura_stramonium_final_busco', 'Datura_stramonium_final_busco', 'Datura_stramonium_final_busco', 'Solanum_sisymbriifolium_final_busco', 'Solanum_sisymbriifolium_final_busco', 'Solanum_sisymbriifolium_final_busco', 'Solanum_sisymbriifolium_final_busco', 'Us9_final_busco', 'Us9_final_busco', 'Us9_final_busco', 'Us9_final_busco', 'Yn12_final_busco', 'Yn12_final_busco', 'Yn12_final_busco', 'Yn12_final_busco', 'Yn17_final_busco', 'Yn17_final_busco', 'Yn17_final_busco', 'Yn17_final_busco', 'Yn36_final_busco', 'Yn36_final_busco', 'Yn36_final_busco', 'Yn36_final_busco', 'Solanum_macrocarpon_hifiasm_final_busco', 'Solanum_macrocarpon_hifiasm_final_busco', 'Solanum_macrocarpon_hifiasm_final_busco', 'Solanum_macrocarpon_hifiasm_final_busco', 'Solanum_ochranthum_final_busco', 'Solanum_ochranthum_final_busco', 'Solanum_ochranthum_final_busco', 'Solanum_ochranthum_final_busco', 'Przewalskia_tangutica_final_busco', 'Przewalskia_tangutica_final_busco', 'Przewalskia_tangutica_final_busco', 'Przewalskia_tangutica_final_busco', 'Datura_inoxia_purged_busco', 'Datura_inoxia_purged_busco', 'Datura_inoxia_purged_busco', 'Datura_inoxia_purged_busco')
my_species <- factor(my_species)
my_species <- factor(my_species,levels(my_species)[c(length(levels(my_species)):1)]) # reorder your species here just by changing the values in the vector :
my_percentage <- c(48.3, 49.9, 0.2, 1.6, 93.1, 3.6, 0.5, 2.8, 94.6, 3.4, 0.2, 1.8, 2.3, 96.8, 0.1, 0.8, 6.3, 92.7, 0.1, 0.9, 83.9, 14.0, 0.2, 1.9, 40.5, 57.6, 0.2, 1.7, 94.4, 3.3, 0.3, 2.0, 93.8, 3.6, 0.4, 2.2, 60.1, 37.6, 0.2, 2.1, 79.1, 19.0, 0.3, 1.6, 12.6, 85.8, 0.1, 1.5, 9.8, 88.1, 0.1, 2.0, 6.2, 92.8, 0.1, 0.9, 92.5, 5.1, 0.3, 2.1, 62.1, 35.9, 0.3, 1.7, 56.4, 41.2, 0.2, 2.2, 52.6, 45.6, 0.2, 1.6, 39.9, 57.6, 0.4, 2.1, 85.0, 12.9, 0.3, 1.8, 93.7, 3.9, 0.2, 2.2, 49.9, 48.7, 0.1, 1.3, 94.7, 3.1, 0.1, 2.1, 82.7, 3.0, 0.4, 13.9)
my_values <- c(2873, 2970, 13, 94, 5537, 217, 32, 164, 5630, 200, 11, 109, 136, 5758, 4, 52, 374, 5515, 6, 55, 4991, 835, 13, 111, 2407, 3429, 11, 103, 5618, 195, 16, 121, 5584, 215, 22, 129, 3573, 2236, 11, 130, 4707, 1128, 16, 99, 747, 5103, 7, 93, 586, 5244, 6, 114, 370, 5519, 6, 55, 5503, 302, 18, 127, 3693, 2134, 18, 105, 3358, 2450, 9, 133, 3132, 2715, 13, 90, 2376, 3426, 22, 126, 5060, 770, 17, 103, 5576, 235, 14, 125, 2970, 2898, 8, 74, 5635, 183, 8, 124, 4921, 181, 24, 824)

######################################
######################################
######################################
# Code to produce the graph
labsize = 1
if (length(levels(my_species)) > 10){
 labsize = 0.66
}
print("Plotting the figure ...")
category <- c(rep(c("S","D","F","M"),c(1)))
category <-factor(category)
category = factor(category,levels(category)[c(4,1,2,3)])
df = data.frame(my_species,my_percentage,my_values,category)

figure <- ggplot() + 
  
  geom_bar(aes(y = my_percentage, x = my_species, fill = category), position = position_stack(reverse = TRUE), data = df, stat="identity", width=my_bar_height) + 
  coord_flip() + 
  theme_gray(base_size = 8) + 
  scale_y_continuous(labels = c("0","20","40","60","80","100"), breaks = c(0,20,40,60,80,100)) + 
  scale_fill_manual(values = my_colors,labels =c(" Complete (C) and single-copy (S)  ",
                                                 " Complete (C) and duplicated (D)",
                                                 " Fragmented (F)  ",
                                                 " Missing (M)")) +   
  ggtitle(my_title) + 
  xlab("") + 
  ylab("\n%BUSCOs") + 

  theme(plot.title = element_text(family=my_family, hjust=0.5, colour = "black", size = rel(2.2)*my_size_ratio, face = "bold")) + 
  theme(legend.position="top",legend.title = element_blank()) + 
  theme(legend.text = element_text(family=my_family, size = rel(1.2)*my_size_ratio)) + 
  theme(panel.background = element_rect(color="#FFFFFF", fill="white")) + 
  theme(panel.grid.minor = element_blank()) + 
  theme(panel.grid.major = element_blank()) +
  theme(axis.text.y = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.text.x = element_text(family=my_family, colour = "black", size = rel(1.66)*my_size_ratio)) + 
  theme(axis.line = element_line(size=1*my_size_ratio, colour = "black")) + 
  theme(axis.ticks.length = unit(.85, "cm")) + 
  theme(axis.ticks.y = element_line(colour="white", size = 0)) + 
  theme(axis.ticks.x = element_line(colour="#222222")) + 
  theme(axis.ticks.length = unit(0.4, "cm")) + 
  theme(axis.title.x = element_text(family=my_family, size=rel(1.2)*my_size_ratio)) + 
  
  guides(fill = guide_legend(override.aes = list(colour = NULL))) +
  guides(fill=guide_legend(nrow=2,byrow=TRUE))
  
  for(i in rev(c(1:length(levels(my_species))))){
    detailed_values <- my_values[my_species==my_species[my_species==levels(my_species)[i]]]
    total_buscos <- sum(detailed_values)
    figure <- figure + 
    annotate("text", label=paste("C:", detailed_values[1] + detailed_values[2], " [S:", detailed_values[1], ", D:", detailed_values[2], "], F:", detailed_values[3], ", M:", detailed_values[4], ", n:", total_buscos, sep=""), 
             y=3, x = i, size = labsize*4*my_size_ratio, colour = "black", hjust=0, family=my_family)
  }
  
ggsave(figure, file=my_output, width = my_width, height = my_height, unit = my_unit)
print("Done")
